name: job-level-envvarible
on: 
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    env:
       king: ashok
       city: repalle
    steps:
      - name: job-level
        run: |
           echo "the jungle king is $king from $city"
           echo "never compare with $king is danger from $city"
           
      - name: step-level2
        run: echo "king is $king city is $city"
  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
        - name: job-level
          run: |
            echo "the jungle king is $king from $city"
            echo "never compare with $king is danger from $city"
     
        
      
    
 
  
      
  
  
