name: secrets and variables
on:
  workflow_dispatch: 
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps: 
    - name: show repository variable
      run: echo "name is${{vars.KING}}"
    - name: about secrets
      env:
        KEY: ${{secrets.API_KEY}}
      run: |
        echo "secret recieved"
        echo $KEY    #key logs are encrypted
        
        
    
