name: without-checkout
on: push
jobs:
  validating-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v5
      - name: dispalying the file content
        run: cat devops.txt
      - name: my hero
        run: ashok
