name: without-matrix
on:
  workflow_dispatch: 
jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: print Os
        run: echo "running on ubuntu os"
  testjob2:
    runs-on: windows-latest
    steps:
      - name: print Os
        run: echo "running on windows os"
